### PR TITLE
Bump webpack peerDependency to include 3

### PR DESCRIPTION
**Pull request by JamieDixon**

### CODE REVIEW

**Comment by sandfox** [comment]
looks good, although `1.14.x - 3.x` seems more concise / readable to me? (but maybe thats _bad_ semver-ing ??

**Comment by JamieDixon** [comment]
@sandfox I was struggling to find docs on the versioning stuff. I hacked together what seemed "OK" but happy to change if there's a better syntax!

**Comment by sandfox** [comment]
I really don't know if it's any better computering wise but I think it looks easier to read (opinions!)

https://semver.npmjs.com/ is a good resource for semver

**Comment by sandfox** [comment]
oh fuck it, I'm turning this into a _500 lines - LGTM, 1 line - 40 changes_ thing aren't I.
Feel free to merge it!

**Comment by JamieDixon** [comment]
Oooh https://semver.npmjs.com/ is super useful. I'm gonna make this change.

**Pull request merged**
